version: 0.0
os: linux
files:
  - source: /myapp
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
